import { CarTypes } from "../types/CarsTypes";

export const carsData: CarTypes[] = [
    {
        brand: "Hyundai",
        model: "Tucson BVA",
        slug: "hyundai-tucson-bva",
        transmission: "Automatique",
        price: 520,
        year: 2021,
        seat: 5,
        doors: 4,
        color: '#000000',
        fuelType: 'Essence',
        imageUrl: '/assets/cars/tucson-bva/1.PNG',
        images: [
            '/assets/cars/tucson-bva/1.PNG',
            '/assets/cars/tucson-bva/2.PNG',
            '/assets/cars/tucson-bva/3.PNG',
            '/assets/cars/tucson-bva/4.PNG',
        ],
        description: "Le Hyundai Tucson BVA est un SUV compact polyvalent et confortable. Il est parfait pour les escapades en famille et les activités de plein air.",
        availability: true,
        bag: 4,
        trunk: "541 litres",
        km: "15 000",
        airbag: true,
        navigation: "GPS intégré",
        moteur: "1.6L Turbo",
        acceleration: "9 secondes de 0 à 100 km/h",
        consommationCarburant: "7 litres/100 km",
        features: ["Climatisation automatique", "Vitres électriques", "Toit ouvrant panoramique (en option)"],
    },
    {
        brand: "Hyundai",
        model: "Accent",
        year: 2024,
        slug: "hyundai-accent",
        price: 350,
        seat: 5,
        doors: 4,
        color: "Gris",
        fuelType: "Essence",
        imageUrl: "/assets/cars/hyundai/1.PNG",
        images: [
            "/assets/cars/hyundai/1.PNG",
            "/assets/cars/hyundai/2.PNG",
            "/assets/cars/hyundai/3.PNG"
        ],
        description: "La Hyundai Accent est une citadine économique et fiable. Elle est parfaite pour les déplacements quotidiens et les petits trajets en ville.",
        availability: true,
        bag: 2,
        trunk: "339 litres",
        km: "10 000",
        airbag: true,
        navigation: "GPS en option",
        transmission: "Manuelle",
        moteur: "1.4L",
        acceleration: "12 secondes de 0 à 100 km/h",
        consommationCarburant: "6 litres/100 km",
        features: ["Climatisation", "Vitres électriques", "Radio MP3"],
    },
    {
        brand: "Dacia",
        model: "Logan",
        year: 2023,
        slug: "dacia-logan",
        price: 280,
        seat: 5,
        doors: 5,
        color: "Bleu",
        fuelType: "Essence/GPL",
        imageUrl: "/assets/cars/dacia-logan/1.PNG",
        images: [
            "/assets/cars/dacia-logan/1.PNG",
            "/assets/cars/dacia-logan/2.PNG",
            "/assets/cars/dacia-logan/3.PNG"],
        description: "La Dacia Logan est une berline spacieuse et économique. Elle est parfaite pour les familles et les longs trajets.",
        availability: true,
        bag: 3,
        trunk: "528 litres",
        km: "25 000",
        airbag: true,
        navigation: "GPS en option",
        transmission: "Manuelle",
        moteur: "0.9L GPL",
        acceleration: "14 secondes de 0 à 100 km/h",
        consommationCarburant: "5 litres/100 km (GPL)",
        features: ["Climatisation", "Vitres électriques", "Radio USB"],
    },
    {
        brand: "Hyundai",
        model: "Tucson",
        year: 2023,
        slug: "hyundai-tucson",
        price: 480,
        seat: 5,
        doors: 5,
        color: "Noir",
        fuelType: "Essence",
        imageUrl: "/assets/cars/tucson/1.PNG",
        images: [
            "/assets/cars/tucson/1.PNG",
            "/assets/cars/tucson/2.PNG",
            "/assets/cars/tucson/4.PNG",
            "/assets/cars/tucson/5.PNG"],
        description: "Le Hyundai Tucson est un SUV compact polyvalent et confortable. Il est parfait pour les escapades en famille et les activités de plein air.",
        availability: true,
        bag: 4,
        trunk: "541 litres",
        km: "15 000",
        airbag: true,
        navigation: "GPS intégré",
        transmission: "Automatique",
        moteur: "1.6L Turbo",
        acceleration: "9 secondes de 0 à 100 km/h",
        consommationCarburant: "7 litres/100 km",
        features: ["Climatisation automatique", "Vitres électriques", "Toit ouvrant panoramique (en option)"],
    },
    {
        brand: "Volkswagen",
        model: "Tiguan",
        year: 2022,
        slug: "volkswagen-tiguan",
        price: 550,
        seat: 5,
        doors: 5,
        color: "Blanc",
        fuelType: "Essence",
        imageUrl: "/assets/cars/volkswagen-tiguan/1.PNG",
        images: [
            "/assets/cars/volkswagen-tiguan/1.PNG",
            "/assets/cars/volkswagen-tiguan/2.PNG",
            "/assets/cars/volkswagen-tiguan/3.PNG"],
        description: "Le Volkswagen Tiguan est un SUV compact familial spacieux et confortable. Il est parfait pour les longs trajets et les escapades en famille.",
        availability: true,
        bag: 4,
        trunk: "615 litres",
        km: "30 000",
        airbag: true,
        navigation: "GPS intégré",
        transmission: "Automatique",
        moteur: "1.5L TSI",
        acceleration: "8 secondes de 0 à 100 km/h",
        consommationCarburant: "6 litres/100 km",
        features: ["Climatisation automatique", "Vitres électriques", "Jantes en alliage"],
    },
    {
        brand: "Volkswagen",
        model: "T-Roc",
        year: 2023,
        slug: "volkswagen-troc",
        price: 420,
        seat: 5,
        doors: 5,
        color: "Rouge",
        fuelType: "Essence",
        imageUrl: "/assets/cars/volkswagen-troc/1.PNG",
        images: [
            "/assets/cars/volkswagen-troc/1.PNG",
            "/assets/cars/volkswagen-troc/2.PNG",
             "/assets/cars/volkswagen-troc/3.PNG"
        ],
        description: "Le Volkswagen T-Roc est un SUV urbain stylé et dynamique. Il est parfait pour les citadins actifs et les virées entre amis.",
        availability: true,
        bag: 3,
        trunk: "445 litres",
        km: "12 000",
        airbag: true,
        navigation: "GPS en option",
        transmission: "Manuelle",
        moteur: "1.0L TSI",
        acceleration: "11 secondes de 0 à 100 km/h",
        consommationCarburant: "5 litres/100 km",
        features: ["Climatisation", "Vitres électriques", "Jantes en aluminium"],
    },
    {
        brand: "Renault",
        model: "Clio 5",
        year: 2024,
        slug: "renault-clio-5",
        price: 320,
        seat: 5,
        doors: 5,
        color: "Jaune",
        fuelType: "Essence",
        imageUrl: "/assets/cars/clio/clio0.png ",
        images: [
            "/assets/cars/clio/clio1.webp",
            "/assets/cars/clio/clio2.webp",
            "/assets/cars/clio/clio3.webp",
            "/assets/cars/clio/clio4.webp",
            "/assets/cars/clio/clio5.webp "
        ],
        description: "La Renault Clio 5 est une citadine polyvalente et moderne. Elle est parfaite pour les déplacements quotidiens et les virées en week-end.",
        availability: true,
        bag: 2,
        trunk: "391 litres",
        km: "5 000",
        airbag: true,
        navigation: "GPS en option",
        transmission: "Manuelle",
        moteur: "1.0L TCe",
        acceleration: "10 secondes de 0 à 100 km/h",
        consommationCarburant: "4 litres/100 km",
        features: ["Climatisation", "Vitres électriques", "Système audio Bluetooth"],
    },
];
